stages:
  - postinstall
  - tests
  - lint

########################################
# POSTINSTALL
########################################

postinstall:
  image: before-postinstall
  stage: postinstall
  script:
    - yunohost tools postinstall -d domain.tld -p the_password --ignore-dyndns

########################################
# TESTS
########################################

.test-stage:
  image: after-postinstall
  stage: tests
  before_script:
    - apt-get install python-pip -y
    - mkdir -p .pip
    - python -m pip install -U pip
    - python -m pip --cache-dir=.pip install tox
    - pushd src/yunohost/tests
    - >
       if [ ! -d "./apps" ]; then
         git clone https://github.com/YunoHost/test_apps ./apps
       fi
    - cd apps
    - git pull > /dev/null 2>&1
    - popd
    - export PYTEST_ADDOPTS="--color=yes"
  cache:
    paths: 
      - .pip
      - .tox
      - src/yunohost/tests/apps
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"

root-tests:
  extends: .test-stage
  script:
    - tox -e py27 tests

test-apps:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_apps.py

test-appscatalog:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_appscatalog.py

test-appurl:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_appurl.py

test-backuprestore:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_backuprestore.py

test-changeurl:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_changeurl.py

test-permission:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_permission.py

test-settings:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_settings.py

test-user-group:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_user-group.py
    
test-regenconf:
  extends: .test-stage
  script:
    - tox -e py27 src/yunohost/tests/test_regenconf.py

########################################
# LINTER
########################################

.lint-stage:
  image: before-postinstall
  stage: lint
  before_script:
    - apt-get install python-pip -y
    - mkdir -p .pip
    - python -m pip install -U pip
    - python -m pip --cache-dir=.pip install tox
  cache:
    paths: 
      - .pip
      - .tox
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"

lint:
  extends: .lint-stage
  allow_failure: true
  script:
    - tox -e lint

# Disabled, waiting for buster
#format-check:
#  extends: .lint-stage
#  script:
#    - black --check --diff