language: python

matrix:
  allow_failures:
    - env: TOXENV=py27-lint
    - env: TOXENV=py37-lint
    - env: TOXENV=py37-invalidcode
  include:
    - python: 2.7
      env: TOXENV=py27-lint
    - python: 2.7
      env: TOXENV=py27-invalidcode
    - python: 3.7
      env: TOXENV=py37-lint
    - python: 3.7
      env: TOXENV=py37-invalidcode

install:
  - pip install tox

script:
  - tox
