language: python

matrix:
  allow_failures:
    - env: TOXENV=lint
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=lint

install:
  - pip install tox

script:
  - tox
